#!/usr/bin/env node
/* Builds src/index.html from src/page/ (head, body, app) and src/site-lists.js,
   as ONE file with the module inlined, so it works opened from disk, from
   GitHub, as the claude.ai copy and served by the Worker alike. Gary opened
   src/index.html from disk on 08/10 and saw an empty page: a module import
   is blocked there.

   Usage:  node scripts/build-page.mjs           writes src/index.html
           node scripts/build-page.mjs --check   exit 1 if src/index.html is stale */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), "..");
const read = f => fs.readFileSync(path.join(ROOT, f), "utf8");
const head = read("src/page/head.html");
const body = read("src/page/body.html");
const app = read("src/page/app.js");
/* The module, with its exports turned into plain declarations. */
const mod = read("src/site-lists.js").replace(/^export function /gm, "function ").replace(/^export const /gm, "const ");
const page = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<!-- GENERATED by scripts/build-page.mjs from src/page/ and src/site-lists.js.
     Do not edit this file: edit those and run the script. One file on
     purpose, so it opens from disk, from GitHub and behind the Worker alike.
     Plan and decisions: BRIEF.md. -->
${head}</head><body>
${body}
<script>
${mod}
${app}
</script>
</body></html>
`;
const out = path.join(ROOT, "src", "index.html");
if(process.argv.includes("--check")){
  const current = fs.existsSync(out) ? fs.readFileSync(out, "utf8") : "";
  if(current !== page){ console.error("src/index.html is stale: run node scripts/build-page.mjs"); process.exit(1); }
  console.log("src/index.html is up to date");
}else{
  fs.writeFileSync(out, page);
  console.log("wrote src/index.html (" + page.length + " bytes)");
}
